### ISSUE TITLE
Resizing image while using app

### ISSUE THREAD

**Issue by librarianmage** [allen-garvey/dithermark#20]
Hello,
dithering images is often used in conjunction with shrinking the image, in order to reduce the perceptual color loss while drastically reducing file size. Is there a way this could be added into the app?

**Comment by allen-garvey** [comment]
There is already a way to do shrink images, though you are not able to specify the exact image dimensions. If you load an image and increase the pixelation in the image tab and then export with the size setting set to "actual", you will get a smaller image.

Also as well, if a large image is imported and the "shrink large images" setting is checked in the settings tab the image will be shrunk proportionally so the largest dimension (width or height) is 1200 pixels.

**Comment by allen-garvey** [comment]
Hmm, looking at this now, there appears to be a bug with the size setting when exporting, it is supposed to function as described in my previous comment, but it doesn't look like it is working, I will work on a fix.
