### ISSUE TITLE
export with exact colors

### ISSUE THREAD

**Issue by latsami** [allen-garvey/dithermark#32]
Hello,
thanks for the great software, I show it to students every year :)

It's the first time I use it for colorwork and not only b&w.
I want a 5 color palette, but when exporting in png, it outputs me 19 colors.
When indexing colors to 5 colors in Gimp, the image is altered.
Any way to export with the exact palette?

**Comment by allen-garvey** [comment]
Are you using the post dither filters or the outline filter? As that is the only way I can think of where you can possibly have more colors than are specified in the color count. I have just re-tested now and I am seeing the expected number of colors in GIMP.

If that is not the case, can you share some more details of your operating system / browser, and what settings you are using?

**Comment by latsami** [comment]
Hello,
you're right, it's because I used some post-dither treatments. Thanks for solving this. Way more practical to have exact colors :)
